name: 'Buildah'
description: 'Build ICO images using buildah build-using-dockerfile'
author: 'Lucas Bickel <hairmare@purplehaze.ch>'
inputs:
  tag:
    description: >-
      Specifies the name which will be assigned to the resulting image
      if the build process completes successfully.
    required: true
  file:
    description: >-
      Specifies a Dockerfile which contains instructions for building
      the image, either a local file or an http or https URL.
    default: 'Dockerfile'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'build-using-dockerfile'
    - '--userns=host'
    - "--file='${{ inputs.file }}'"
    - "--tag='${{ inputs.tag }}'"
